name: Deploy Node.js project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  NODE_VERSION: '18.x' # Use '20.x' if your local node version was v20

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Node.js Environment'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          popd

      # This replaces the hardcoded secret check with your linked Azure app instance
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'cybexbi-otb-api'
          slot-name: 'production'
          package: '.'
